/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.penjualan;

import dao.BasePresenter;
import dao.DBConnection;
import dao.PelangganModel;
import dao.PenjualanModel;
import dao.TiketModel;
import java.awt.event.KeyEvent;
import java.io.InputStream;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import ui.pelanggan.PelangganPresenter;
import ui.tiket.TiketPresenter;
import utils.Config;
import utils.DialogFactory;
import utils.StringHelper;

/**
 *
 * @author EKA PRATAMA
 */
public class Penjualan extends javax.swing.JFrame implements PenjualanMvpView {

    private DefaultTableModel TabModel;
    private PenjualanPresenterImpl mPresenter;
    private PelangganPresenter mPelangganPresenter;
    private TiketPresenter mTiketPresenter;

    /**
     * Creates new form Ticket Booking
     */
    public Penjualan() {
        initComponents();
        formReadyToFilled(false);
        setDefaultButton();
        TabModel = new DefaultTableModel(null, Config.TABLE_HEADER_PENJUALAN);
        mPelangganPresenter = new PelangganPresenter();
        mTiketPresenter = new TiketPresenter();
        mPresenter = new PenjualanPresenterImpl();
        mPresenter.attachView(this);
    }

    public void addDataIntoTable() {
        try {
            tblPenjualan.setModel(TabModel);
            Double harga = Double.parseDouble(txtHarga.getText());
            int qty = Integer.parseInt(txtQuantity.getText());

            String kolom1 = txtKodeTransaksi.getText();
            String kolom2 = lblIdPelanggan.getText();
            String kolom3 = txtPelangganName.getText();
            String kolom4 = lblIdTiket.getText();;
            String kolom5 = txtMaskapai.getText();
            String kolom6 = txtKelas.getText();
            String kolom7 = txtTujuan.getText();
            String kolom8 = txtHarga.getText();
            String kolom9 = txtQuantity.getText();
            String kolom10 = String.valueOf(harga * qty);

            String[] kolom = {kolom1, kolom2, kolom3, kolom4, kolom5, kolom6, kolom7, kolom8, kolom9, kolom10};
            TabModel.addRow(kolom);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Data gagal disimpan");
        }
    }

    private void hapusdatadaritabel() {
        int a = tblPenjualan.getSelectedRow();
        if (a == -1) {
        }
        TabModel.removeRow(a);
    }

    private void showPelanggan() {
        DefaultTableModel data = new DefaultTableModel(null, Config.TABLE_HEADER_PELANGGAN);
        tblPelanggan.setModel(data);
        ArrayList<PelangganModel> listPelanggan = mPelangganPresenter.getData();
        for (PelangganModel item : listPelanggan) {
            String[] kolom = {item.idPelanggan, item.nama, item.alamat, item.telepon};
            data.addRow(kolom);
        }
    }

    private void showTiket() {
        DefaultTableModel data = new DefaultTableModel(null, Config.TABLE_HEADER_TIKET);
        tblTiket.setModel(data);
        ArrayList<TiketModel> list = mTiketPresenter.getData();
        for (TiketModel item : list) {
            String[] kolom = {item.kodeTicket, item.maskapai, item.kelas, item.tujuan, String.valueOf(item.harga), item.status};
            data.addRow(kolom);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogPelanggan = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPelanggan = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txtSearchPelanggan = new javax.swing.JTextField();
        btnSearchPelanggan = new javax.swing.JButton();
        dialogTiket = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblTiket = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        txtSearchTiket = new javax.swing.JTextField();
        btnSearchTiket = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtKodeTransaksi = new javax.swing.JTextField();
        lblIdTiket = new javax.swing.JLabel();
        txtPelangganName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        btnCariTiket = new javax.swing.JButton();
        btnKurang = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPenjualan = new javax.swing.JTable();
        txtQuantity = new javax.swing.JTextField();
        simpanBT = new javax.swing.JButton();
        tambahBT = new javax.swing.JButton();
        txtKembali = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        txtBayar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTanggalBerangkat = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        txtPelangganTelp = new javax.swing.JTextField();
        btnCariPelanggan = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtTujuan = new javax.swing.JTextField();
        txtMaskapai = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtKelas = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        lblIdPelanggan = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        dialogPelanggan.setMinimumSize(new java.awt.Dimension(460, 386));
        dialogPelanggan.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        dialogPelanggan.setResizable(false);
        dialogPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dialogPelangganMouseClicked(evt);
            }
        });

        tblPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPelangganMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblPelanggan);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Data Pelanggan");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ketikan Kriteria Pencarian", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        txtSearchPelanggan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchPelangganKeyPressed(evt);
            }
        });

        btnSearchPelanggan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSearchPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Pilih.gif"))); // NOI18N
        btnSearchPelanggan.setText("Cari");
        btnSearchPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchPelangganActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(txtSearchPelanggan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout dialogPelangganLayout = new javax.swing.GroupLayout(dialogPelanggan.getContentPane());
        dialogPelanggan.getContentPane().setLayout(dialogPelangganLayout);
        dialogPelangganLayout.setHorizontalGroup(
            dialogPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogPelangganLayout.setVerticalGroup(
            dialogPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        dialogTiket.setMinimumSize(new java.awt.Dimension(460, 386));
        dialogTiket.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        dialogTiket.setResizable(false);
        dialogTiket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dialogTiketMouseClicked(evt);
            }
        });

        tblTiket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTiket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTiketMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblTiket);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Data Maskapai");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ketikan Kriteria Pencarian", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        txtSearchTiket.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchTiketKeyPressed(evt);
            }
        });

        btnSearchTiket.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSearchTiket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Pilih.gif"))); // NOI18N
        btnSearchTiket.setText("Cari");
        btnSearchTiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchTiketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(txtSearchTiket)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchTiket, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchTiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchTiket, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout dialogTiketLayout = new javax.swing.GroupLayout(dialogTiket.getContentPane());
        dialogTiket.getContentPane().setLayout(dialogTiketLayout);
        dialogTiketLayout.setHorizontalGroup(
            dialogTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogTiketLayout.setVerticalGroup(
            dialogTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Transaksi Tiket Pesawat");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, -1));

        jLabel2.setText("No. Trans");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 90, -1));

        txtKodeTransaksi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtKodeTransaksi.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        txtKodeTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeTransaksiActionPerformed(evt);
            }
        });
        jPanel1.add(txtKodeTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 113, 30));

        lblIdTiket.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(lblIdTiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 61, -1));

        txtPelangganName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPelangganNameKeyTyped(evt);
            }
        });
        jPanel1.add(txtPelangganName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 290, -1));

        jLabel8.setText("Jumlah Tiket");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, 140, -1));

        txtHarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHargaKeyTyped(evt);
            }
        });
        jPanel1.add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 290, -1));

        btnCariTiket.setText("...");
        btnCariTiket.setToolTipText("Cari barang");
        btnCariTiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariTiketActionPerformed(evt);
            }
        });
        jPanel1.add(btnCariTiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 30, 20));

        btnKurang.setText("-");
        btnKurang.setToolTipText("Kurangi transaksi");
        btnKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKurangActionPerformed(evt);
            }
        });
        jPanel1.add(btnKurang, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 350, 90, 20));

        btnTambah.setText("+");
        btnTambah.setToolTipText("Tambah transaksi");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jPanel1.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 350, 90, 20));

        tblPenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPenjualanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPenjualan);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 890, 180));

        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });
        txtQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQuantityKeyTyped(evt);
            }
        });
        jPanel1.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, 210, -1));

        simpanBT.setText("Simpan");
        simpanBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanBTActionPerformed(evt);
            }
        });
        jPanel1.add(simpanBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 660, 100, -1));

        tambahBT.setText("Tambah");
        tambahBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBTActionPerformed(evt);
            }
        });
        jPanel1.add(tambahBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, 100, -1));

        txtKembali.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtKembali.setForeground(new java.awt.Color(255, 0, 0));
        txtKembali.setText("0");
        txtKembali.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKembaliKeyTyped(evt);
            }
        });
        jPanel1.add(txtKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 650, 150, -1));

        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(255, 0, 0));
        txtTotal.setText("0");
        txtTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTotalKeyTyped(evt);
            }
        });
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 590, 150, -1));

        txtBayar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtBayar.setForeground(new java.awt.Color(255, 0, 0));
        txtBayar.setText("0");
        txtBayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBayarKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBayarKeyTyped(evt);
            }
        });
        jPanel1.add(txtBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 620, 150, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText(" Kembali");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 650, 60, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Total");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 590, 50, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Bayar");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 620, 50, 20));

        jLabel11.setText("Tanggal Keberangkatan");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, -1, -1));

        txtTanggalBerangkat.setToolTipText("");
        txtTanggalBerangkat.setDateFormatString("dd MMMM yyyy");
        jPanel1.add(txtTanggalBerangkat, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 280, -1));

        jLabel12.setText("Telepon");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 61, -1));

        txtPelangganTelp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPelangganTelpKeyTyped(evt);
            }
        });
        jPanel1.add(txtPelangganTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 290, -1));

        btnCariPelanggan.setText("...");
        btnCariPelanggan.setToolTipText("Cari barang");
        btnCariPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariPelangganActionPerformed(evt);
            }
        });
        jPanel1.add(btnCariPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 30, 20));

        jLabel13.setText("Tujuan-");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 61, -1));

        txtTujuan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTujuanKeyTyped(evt);
            }
        });
        jPanel1.add(txtTujuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 290, -1));

        txtMaskapai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMaskapaiKeyTyped(evt);
            }
        });
        jPanel1.add(txtMaskapai, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 280, -1));

        jLabel15.setText("Maskapai");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 80, -1));

        jLabel16.setText("Kelas");
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 61, -1));

        txtKelas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKelasKeyTyped(evt);
            }
        });
        jPanel1.add(txtKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 280, -1));

        jLabel17.setText("Harga");
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 61, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 900, 20));

        jLabel5.setText("Pembeli - ");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 80, -1));

        lblIdPelanggan.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(lblIdPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 61, -1));

        jButton1.setText("Check");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 620, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariTiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariTiketActionPerformed
        dialogTiket.setLocationRelativeTo(null);
        showTiket();
        dialogTiket.setVisible(true);
        txtSearchTiket.setText("");
    }//GEN-LAST:event_btnCariTiketActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        Date date = new Date();
        txtTanggalBerangkat.setDate(date);
    }//GEN-LAST:event_formWindowActivated

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void simpanBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanBTActionPerformed
        // TODO add your handling code here:
        if (txtKodeTransaksi.getText().equals("") || txtPelangganName.getText().equals("") || txtBayar.getText().equals("0") || txtKembali.getText().equals("0")) {
            JOptionPane.showMessageDialog(null, "Lengkapi inputan penjualan barang");
        } else {
            save();
//            int pesan = JOptionPane.showConfirmDialog(null, "Cetak Kwitansi Nota", "Cetak", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
//            if (pesan == JOptionPane.YES_OPTION) {
//                cetak_nota();
//            }
            clearForm();
            TabModel.getDataVector().removeAllElements();
            TabModel.fireTableDataChanged();
        }
    }//GEN-LAST:event_simpanBTActionPerformed

    private void tambahBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBTActionPerformed
        if (tambahBT.getText().equalsIgnoreCase("tambah")) {
            tambahBT.setText("Batal");
            formReadyToFilled(true);
            clearForm();
            txtKodeTransaksi.setText(mPresenter.generateFormId());
            txtPelangganName.requestFocus();
            txtKodeTransaksi.setEnabled(false);
            simpanBT.setEnabled(true);
            btnTambah.setEnabled(true);
            btnKurang.setEnabled(true);
            btnCariTiket.setEnabled(true);
            btnCariPelanggan.setEnabled(true);
        } else {
            clearForm();
            formReadyToFilled(false);
            tambahBT.setText("Tambah");
            TabModel.getDataVector().removeAllElements();
            TabModel.fireTableDataChanged();
            setDefaultButton();
        }
    }//GEN-LAST:event_tambahBTActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        Double harga = Double.parseDouble(txtHarga.getText());
        Double jml = Double.parseDouble(txtQuantity.getText());
        Double total = Double.parseDouble(txtTotal.getText());

        double subtot = harga * jml;
        txtTotal.setText(Double.toString(subtot));

        double totbay = total + (harga * jml);
        txtTotal.setText(Double.toString(totbay));

        addDataIntoTable();

        txtTujuan.setText("");
        txtMaskapai.setText("");
        txtKelas.setText("");
        txtHarga.setText("");
        txtQuantity.setText("");
    }//GEN-LAST:event_btnTambahActionPerformed

    private void dialogPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dialogPelangganMouseClicked
        handleOnClickDialogPelanggan();
    }//GEN-LAST:event_dialogPelangganMouseClicked

    private void btnKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKurangActionPerformed
        // TODO add your handling code here:
        int baris = tblPenjualan.getSelectedRow();
        Double qty = Double.parseDouble(tblPenjualan.getModel().getValueAt(baris, 8).toString());
        Double total = Double.parseDouble(txtTotal.getText());
        Double harga = Double.parseDouble(tblPenjualan.getModel().getValueAt(baris, 7).toString());

        double totbay = total - (harga * qty);
        txtTotal.setText(Double.toString(totbay));
        hapusdatadaritabel();
    }//GEN-LAST:event_btnKurangActionPerformed

    private void tblPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPelangganMouseClicked
        handleOnClickDialogPelanggan();
    }//GEN-LAST:event_tblPelangganMouseClicked

    private void txtSearchPelangganKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchPelangganKeyPressed

    }//GEN-LAST:event_txtSearchPelangganKeyPressed

    private void btnSearchPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchPelangganActionPerformed

        if (StringHelper.isNotEmpty(txtSearchPelanggan.getText())) {
            mPelangganPresenter.searchById(tblPelanggan, txtSearchPelanggan.getText());
        } else {
            DialogFactory.dialogError("", "Masukan kriteria pencarian");
        }
    }//GEN-LAST:event_btnSearchPelangganActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        ImageIcon img = new ImageIcon("src/gambar/kredit.png");
        setIconImage(img.getImage());
    }//GEN-LAST:event_formWindowOpened

    private void txtBayarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBayarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Double total = Double.parseDouble(txtTotal.getText());
            Double bayar = Double.parseDouble(txtBayar.getText());
            if (bayar < total) {
                JOptionPane.showMessageDialog(null, "Jumlah bayar tidak mencukupi");
                txtBayar.requestFocus();
            } else {
                double kembali = bayar - total;
                txtKembali.setText(Double.toString(kembali));
            }
        }
    }//GEN-LAST:event_txtBayarKeyPressed

    private void tblPenjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPenjualanMouseClicked
        tblPenjualan.setRowSelectionAllowed(true);
        int a = tblPenjualan.getSelectedRow();
//        String kolom1 =     tblPenjualan.getValueAt(a, 0).toString();
//        String kolom2 = tblPenjualan.getValueAt(a, 1).toString();
//        String kolom3 = tblPenjualan.getValueAt(a, 2).toString();
//        String kolom4 = tblPenjualan.getValueAt(a, 3).toString();
//        String kolom5 = tblPenjualan.getValueAt(a, 4).toString();

        String idPelanggan = tblPenjualan.getValueAt(a, 1).toString();
        String idTiket = tblPenjualan.getValueAt(a, 3).toString();
    }//GEN-LAST:event_tblPenjualanMouseClicked

    private void txtQuantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyTyped
        // TODO add your handling code here:
        //validasi data harus angka atau tombol backspace
        char karakter = evt.getKeyChar();
        if (!(Character.isDigit(karakter) || karakter == KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtQuantityKeyTyped

    private void txtTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalKeyTyped
        // TODO add your handling code here:
        //validasi data harus angka atau tombol backspace
        char karakter = evt.getKeyChar();
        if (!(Character.isDigit(karakter) || karakter == KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTotalKeyTyped

    private void txtKembaliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKembaliKeyTyped
        // TODO add your handling code here:
        //validasi data harus angka atau tombol backspace
        char karakter = evt.getKeyChar();
        if (!(Character.isDigit(karakter) || karakter == KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtKembaliKeyTyped

    private void txtPelangganNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPelangganNameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPelangganNameKeyTyped

    private void txtBayarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBayarKeyTyped
        // TODO add your handling code here:
        //validasi data harus angka atau tombol backspace
        char karakter = evt.getKeyChar();
        if (!(Character.isDigit(karakter) || karakter == KeyEvent.VK_BACK_SPACE || karakter == KeyEvent.VK_ENTER)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtBayarKeyTyped

    private void txtHargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHargaKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if (!(Character.isDigit(karakter) || karakter == KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtHargaKeyTyped

    private void txtPelangganTelpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPelangganTelpKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPelangganTelpKeyTyped

    private void btnCariPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariPelangganActionPerformed
        dialogPelanggan.setLocationRelativeTo(null);
        showPelanggan();
        dialogPelanggan.setVisible(true);
        txtSearchPelanggan.setText("");
    }//GEN-LAST:event_btnCariPelangganActionPerformed

    private void txtTujuanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTujuanKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTujuanKeyTyped

    private void txtMaskapaiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaskapaiKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaskapaiKeyTyped

    private void txtKelasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKelasKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKelasKeyTyped

    private void tblTiketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTiketMouseClicked
        handleOnClickDialogTiket();
    }//GEN-LAST:event_tblTiketMouseClicked

    private void txtSearchTiketKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchTiketKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchTiketKeyPressed

    private void btnSearchTiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchTiketActionPerformed
        if (StringHelper.isNotEmpty(txtSearchTiket.getText())) {
            mTiketPresenter.searchById(tblTiket, txtSearchTiket.getText());
        } else {
            DialogFactory.dialogError("", "Masukkan kriteria pencarian");
        }
    }//GEN-LAST:event_btnSearchTiketActionPerformed

    private void dialogTiketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dialogTiketMouseClicked
        handleOnClickDialogTiket();
    }//GEN-LAST:event_dialogTiketMouseClicked

    private void txtKodeTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodeTransaksiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Double ttl = Double.parseDouble(txtTotal.getText());
        Double bayar = Double.parseDouble(txtBayar.getText());
        Double kembali = Double.parseDouble(txtKembali.getText());
        Double hitung = bayar - ttl;
        System.out.println(hitung);
        txtKembali.setText(Double.toString(hitung));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Penjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariPelanggan;
    private javax.swing.JButton btnCariTiket;
    private javax.swing.JButton btnKurang;
    private javax.swing.JButton btnSearchPelanggan;
    private javax.swing.JButton btnSearchTiket;
    private javax.swing.JButton btnTambah;
    private javax.swing.JDialog dialogPelanggan;
    private javax.swing.JDialog dialogTiket;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblIdPelanggan;
    private javax.swing.JLabel lblIdTiket;
    private javax.swing.JButton simpanBT;
    private javax.swing.JButton tambahBT;
    private javax.swing.JTable tblPelanggan;
    private javax.swing.JTable tblPenjualan;
    private javax.swing.JTable tblTiket;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtKelas;
    private javax.swing.JTextField txtKembali;
    private javax.swing.JTextField txtKodeTransaksi;
    private javax.swing.JTextField txtMaskapai;
    private javax.swing.JTextField txtPelangganName;
    private javax.swing.JTextField txtPelangganTelp;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSearchPelanggan;
    private javax.swing.JTextField txtSearchTiket;
    private com.toedter.calendar.JDateChooser txtTanggalBerangkat;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTujuan;
    // End of variables declaration//GEN-END:variables

    void cetak_nota() {
        try {
            HashMap param = new HashMap();
            param.put("kode", txtKodeTransaksi.getText());
            InputStream is = getClass().getResourceAsStream("/ui/penjualan/nota.jrxml");
            JasperDesign jasperDesign = JRXmlLoader.load(is);
            JasperPrint jasperPrint = JasperFillManager.fillReport(
                    JasperCompileManager.compileReport(jasperDesign), 
                    param, 
                    DBConnection.setConnection());
            JasperViewer.viewReport(jasperPrint, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Nota tidak dapat dicetak!", "Nota", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    @Override
    public void onSucceed(BasePresenter.DataAccessType dataAccessType, PenjualanModel model) {
        DialogFactory.showDialog(model.message);
    }

    @Override
    public void clearForm() {
        txtKodeTransaksi.setText("");
        txtPelangganName.setText("");
        txtPelangganTelp.setText("");
        txtTujuan.setText("");
        txtMaskapai.setText("");
        txtKelas.setText("");
        txtHarga.setText("");
        txtQuantity.setText("");

        txtTotal.setText("0");
        txtBayar.setText("0");
        txtKembali.setText("0");
    }

    @Override
    public void setDefaultButton() {
        tambahBT.setEnabled(true);
        simpanBT.setEnabled(false);
        btnTambah.setEnabled(false);
        btnKurang.setEnabled(false);
        btnCariTiket.setEnabled(false);
        btnCariPelanggan.setEnabled(false);
    }

    @Override
    public void formReadyToFilled(boolean a) {
        txtKodeTransaksi.setEnabled(a);
        txtPelangganName.setEnabled(a);
        txtPelangganTelp.setEnabled(a);
        txtTujuan.setEnabled(a);
        txtMaskapai.setEnabled(a);
        txtKelas.setEnabled(a);
        txtHarga.setEnabled(a);
        txtQuantity.setEnabled(a);

        txtTotal.setEnabled(a);
        txtBayar.setEnabled(a);
        txtKembali.setEnabled(a);
    }

    @Override
    public void onError(BasePresenter.DataAccessType dataAccessType) {
        DialogFactory.dialogError("Pesan", "Terjadi gangguan pada database, silahkan coba lagi");
    }

    private void handleOnClickDialogTiket() {
        int baris = tblTiket.getSelectedRow();
        String id = tblTiket.getModel().getValueAt(baris, 0).toString();
        TiketModel model = mPresenter.findTiketById(id);
        lblIdTiket.setText(model.kodeTicket);
        txtTujuan.setText(model.tujuan);
        txtMaskapai.setText(model.maskapai);
        txtHarga.setText(String.valueOf(model.harga));
        txtKelas.setText(model.kelas);
        dialogTiket.dispose();
    }

    private void handleOnClickDialogPelanggan() {
        int baris = tblPelanggan.getSelectedRow();
        String idPelanggan = tblPelanggan.getModel().getValueAt(baris, 0).toString();
        PelangganModel model = mPresenter.findPelangganById(idPelanggan);
        lblIdPelanggan.setText(model.idPelanggan);
        txtPelangganName.setText(model.nama);
        txtPelangganTelp.setText(model.telepon);
        dialogPelanggan.dispose();
    }

    private void save() {
        try {
            ArrayList<PenjualanModel> list = new ArrayList<>();
            Date skrg = new Date();
            SimpleDateFormat frm = new SimpleDateFormat("yyyy-MM-dd", new Locale("id"));
            String tgl = frm.format(skrg);

            int t = tblPenjualan.getRowCount();
            for (int i = 0; i < t; i++) { // merge into new object
                String idPelanggan = tblPenjualan.getValueAt(i, 1).toString();
                String idTiket = tblPenjualan.getValueAt(i, 3).toString();
                double harga = Double.parseDouble(tblPenjualan.getValueAt(i, 7).toString());
                int jumlah = Integer.parseInt(tblPenjualan.getValueAt(i, 8).toString());
                double total = Double.parseDouble(tblPenjualan.getValueAt(i, 9).toString());

                PelangganModel pelanggan = mPresenter.findPelangganById(idPelanggan);
                TiketModel tiket = mPresenter.findTiketById(idTiket);

                PenjualanModel model = new PenjualanModel();
                model.idPenjualan = txtKodeTransaksi.getText();
                model.tglBerangkat = frm.format(txtTanggalBerangkat.getDate());
                model.idPelanggan = pelanggan.idPelanggan;
                model.namaPelanggan = pelanggan.nama;
                model.alamatPelanggan = pelanggan.alamat;
                model.teleponPelanggan = pelanggan.telepon;

                model.kodeTicket = tiket.kodeTicket;
                model.maskapai = tiket.maskapai;
                model.kelas = tiket.kelas;
                model.tujuan = tiket.tujuan;
                model.harga = tiket.harga;
                model.jumlahBayar = Double.parseDouble(txtTotal.getText());
                model.tiketStatus = tiket.status;

                model.jumlahTiket = jumlah;
                model.totalHarga = total;
                model.createTime = tgl;
                model.status = "berhasil";

                list.add(model);
            }

            mPresenter.save(list);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
