/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.main;

import ui.login.Login;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.ImageIcon;
import ui.karyawan.Pegawai;
import ui.karyawan.PegawaiReport;
import ui.pelanggan.Pelanggan;
import ui.pelanggan.PelangganReport;
import ui.pembatalan.Pembatalan;
import ui.pembatalan.PembatalanReport;
import ui.penjualan.Penjualan;
import ui.penjualan.PenjualanReport;
import ui.tiket.Tiket;
import ui.tiket.TiketReport;

/**
 *
 * @author EKA PRATAMA
 */
public class MenuUtama extends javax.swing.JFrame {

    // Login.getU_nama();
    String nama = Login.username;

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        userJl.setText(nama);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        loginJL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        userJl = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        logoutBT = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        barangBT = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        penjualanBT = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        pembelianBT = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnCustomer = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        xlogout = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        xmaster = new javax.swing.JMenu();
        btnTicket = new javax.swing.JMenuItem();
        menuPelanggan = new javax.swing.JMenuItem();
        menuPelanggan1 = new javax.swing.JMenuItem();
        xtrans = new javax.swing.JMenu();
        xpembelian = new javax.swing.JMenuItem();
        xpenjualan = new javax.swing.JMenuItem();
        xlap = new javax.swing.JMenu();
        pelangganx = new javax.swing.JMenuItem();
        pelangganx1 = new javax.swing.JMenuItem();
        pembatalanx = new javax.swing.JMenuItem();
        xlappembelian = new javax.swing.JMenuItem();
        barangx = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tiket Pesawat");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(237, 237, 244));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Login   :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 56, -1));

        loginJL.setText("jLabel4");
        jPanel1.add(loginJL, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 350, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Welcome To, ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 90, -1));

        userJl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        userJl.setForeground(new java.awt.Color(0, 0, 255));
        userJl.setText("jLabel1");
        jPanel1.add(userJl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        jToolBar1.setBackground(new java.awt.Color(204, 204, 255));
        jToolBar1.setRollover(true);

        logoutBT.setBackground(new java.awt.Color(204, 204, 255));
        logoutBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Hapus.png"))); // NOI18N
        logoutBT.setText("Logout");
        logoutBT.setToolTipText("Klik untuk logout pengguna");
        logoutBT.setFocusable(false);
        logoutBT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logoutBT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        logoutBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBTActionPerformed(evt);
            }
        });
        jToolBar1.add(logoutBT);
        jToolBar1.add(jSeparator1);

        barangBT.setBackground(new java.awt.Color(204, 204, 255));
        barangBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Barang.png"))); // NOI18N
        barangBT.setText("Tiket");
        barangBT.setToolTipText("Klik untuk menambahkan data barang");
        barangBT.setFocusable(false);
        barangBT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        barangBT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barangBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangBTActionPerformed(evt);
            }
        });
        jToolBar1.add(barangBT);
        jToolBar1.add(jSeparator2);

        penjualanBT.setBackground(new java.awt.Color(204, 204, 255));
        penjualanBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/kredit.png"))); // NOI18N
        penjualanBT.setText("Penjualan");
        penjualanBT.setToolTipText("klik untuk menambahkan data transaksi penjualan");
        penjualanBT.setFocusable(false);
        penjualanBT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        penjualanBT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        penjualanBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penjualanBTActionPerformed(evt);
            }
        });
        jToolBar1.add(penjualanBT);
        jToolBar1.add(jSeparator3);

        pembelianBT.setBackground(new java.awt.Color(204, 204, 255));
        pembelianBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Pembelian.png"))); // NOI18N
        pembelianBT.setText("Pembatalan");
        pembelianBT.setToolTipText("klik untuk menambahkan data transaksi pembelian");
        pembelianBT.setFocusable(false);
        pembelianBT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pembelianBT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pembelianBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembelianBTActionPerformed(evt);
            }
        });
        jToolBar1.add(pembelianBT);
        jToolBar1.add(jSeparator4);

        btnCustomer.setBackground(new java.awt.Color(204, 204, 255));
        btnCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Pelanggan.png"))); // NOI18N
        btnCustomer.setText("Pelanggan");
        btnCustomer.setToolTipText("klik untuk menambahkan data transaksi pembelian");
        btnCustomer.setFocusable(false);
        btnCustomer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCustomer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCustomer);
        jToolBar1.add(jSeparator5);

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 255));

        jMenu1.setText("File");

        xlogout.setText("Logout");
        xlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xlogoutActionPerformed(evt);
            }
        });
        jMenu1.add(xlogout);
        jMenu1.add(jSeparator6);

        jMenuItem1.setText("Keluar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        xmaster.setText("Master");

        btnTicket.setText("Tiket");
        btnTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTicketActionPerformed(evt);
            }
        });
        xmaster.add(btnTicket);

        menuPelanggan.setText("Pelanggan");
        menuPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPelangganActionPerformed(evt);
            }
        });
        xmaster.add(menuPelanggan);

        menuPelanggan1.setText("Pegawai");
        menuPelanggan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPelanggan1ActionPerformed(evt);
            }
        });
        xmaster.add(menuPelanggan1);

        jMenuBar1.add(xmaster);

        xtrans.setText("Transaksi");

        xpembelian.setText("Penjualan");
        xpembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xpembelianActionPerformed(evt);
            }
        });
        xtrans.add(xpembelian);

        xpenjualan.setText("Pembatalan");
        xpenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xpenjualanActionPerformed(evt);
            }
        });
        xtrans.add(xpenjualan);

        jMenuBar1.add(xtrans);

        xlap.setText("Laporan");

        pelangganx.setText("Pelanggan");
        pelangganx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelangganxActionPerformed(evt);
            }
        });
        xlap.add(pelangganx);

        pelangganx1.setText("Pegawai");
        pelangganx1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelangganx1ActionPerformed(evt);
            }
        });
        xlap.add(pelangganx1);

        pembatalanx.setText("Pembatalan");
        pembatalanx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembatalanxActionPerformed(evt);
            }
        });
        xlap.add(pembatalanx);

        xlappembelian.setText("Penjualan");
        xlappembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xlappembelianActionPerformed(evt);
            }
        });
        xlap.add(xlappembelian);

        barangx.setText("Tiket");
        barangx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangxActionPerformed(evt);
            }
        });
        xlap.add(barangx);

        jMenuBar1.add(xlap);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jToolBar1.getAccessibleContext().setAccessibleParent(this);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void xlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xlogoutActionPerformed
        // TODO add your handling code here:
        Login LG = new Login();
        LG.setLocationRelativeTo(null);
        LG.setVisible(true);
        dispose();
    }//GEN-LAST:event_xlogoutActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        DateFormat tgl = new SimpleDateFormat("dd MMMM yyyy");
        DateFormat waktu = new SimpleDateFormat("HH:mm:ss");
        String htgl = tgl.format(Calendar.getInstance().getTime());
        String hwaktu = waktu.format(Calendar.getInstance().getTime());
        loginJL.setText(htgl + " - " + hwaktu);
    }//GEN-LAST:event_formWindowActivated

    private void barangxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangxActionPerformed
        TiketReport tiketReport = new TiketReport();
        tiketReport.setLocationRelativeTo(null);
        tiketReport.setVisible(true);
    }//GEN-LAST:event_barangxActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        ImageIcon img = new ImageIcon("src/gambar/kredit.png");
        setIconImage(img.getImage());
    }//GEN-LAST:event_formWindowOpened

    private void xlappembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xlappembelianActionPerformed
        PenjualanReport penjualanReport = new PenjualanReport();
        penjualanReport.setLocationRelativeTo(null);
        penjualanReport.setVisible(true);
    }//GEN-LAST:event_xlappembelianActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void penjualanBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penjualanBTActionPerformed
        Penjualan penjualan = new Penjualan();
        penjualan.setLocationRelativeTo(null);
        penjualan.setVisible(true);
    }//GEN-LAST:event_penjualanBTActionPerformed

    private void xpembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xpembelianActionPerformed
        Penjualan penjualan = new Penjualan();
        penjualan.setLocationRelativeTo(null);
        penjualan.setVisible(true);
    }//GEN-LAST:event_xpembelianActionPerformed

    private void barangBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangBTActionPerformed
        Tiket tiket = new Tiket();
        tiket.setLocationRelativeTo(null);
        tiket.setVisible(true);
    }//GEN-LAST:event_barangBTActionPerformed

    private void btnTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicketActionPerformed
        Tiket tiket = new Tiket();
        tiket.setLocationRelativeTo(null);
        tiket.setVisible(true);
    }//GEN-LAST:event_btnTicketActionPerformed

    private void pembelianBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembelianBTActionPerformed
        Pembatalan batal = new Pembatalan();
        batal.setLocationRelativeTo(null);
        batal.setVisible(true);
    }//GEN-LAST:event_pembelianBTActionPerformed

    private void xpenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xpenjualanActionPerformed
        Pembatalan batal = new Pembatalan();
        batal.setLocationRelativeTo(null);
        batal.setVisible(true);
    }//GEN-LAST:event_xpenjualanActionPerformed

    private void pembatalanxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembatalanxActionPerformed
        PembatalanReport report = new PembatalanReport();
        report.setLocationRelativeTo(null);
        report.setVisible(true);
    }//GEN-LAST:event_pembatalanxActionPerformed

    private void logoutBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBTActionPerformed
        // TODO add your handling code here:
        Login LG = new Login();
        LG.setLocationRelativeTo(null);
        LG.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutBTActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowClosing

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        Pelanggan pelanggan = new Pelanggan();
        pelanggan.setLocationRelativeTo(null);
        pelanggan.setVisible(true);
    }//GEN-LAST:event_btnCustomerActionPerformed

    private void menuPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPelangganActionPerformed
        Pelanggan pelanggan = new Pelanggan();
        pelanggan.setLocationRelativeTo(null);
        pelanggan.setVisible(true);
    }//GEN-LAST:event_menuPelangganActionPerformed

    private void pelangganxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelangganxActionPerformed
        PelangganReport report = new PelangganReport();
        report.setLocationRelativeTo(null);
        report.setVisible(true);
    }//GEN-LAST:event_pelangganxActionPerformed

    private void pelangganx1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelangganx1ActionPerformed
        PegawaiReport report = new PegawaiReport();
        report.setLocationRelativeTo(null);
        report.setVisible(true);
    }//GEN-LAST:event_pelangganx1ActionPerformed

    private void menuPelanggan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPelanggan1ActionPerformed
        Pegawai pegawai = new Pegawai();
        pegawai.setLocationRelativeTo(null);
        pegawai.setVisible(true);
    }//GEN-LAST:event_menuPelanggan1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barangBT;
    private javax.swing.JMenuItem barangx;
    private javax.swing.JButton btnCustomer;
    private javax.swing.JMenuItem btnTicket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel loginJL;
    private javax.swing.JButton logoutBT;
    private javax.swing.JMenuItem menuPelanggan;
    private javax.swing.JMenuItem menuPelanggan1;
    private javax.swing.JMenuItem pelangganx;
    private javax.swing.JMenuItem pelangganx1;
    private javax.swing.JMenuItem pembatalanx;
    private javax.swing.JButton pembelianBT;
    private javax.swing.JButton penjualanBT;
    private javax.swing.JLabel userJl;
    private javax.swing.JMenu xlap;
    private javax.swing.JMenuItem xlappembelian;
    private javax.swing.JMenuItem xlogout;
    private javax.swing.JMenu xmaster;
    private javax.swing.JMenuItem xpembelian;
    private javax.swing.JMenuItem xpenjualan;
    private javax.swing.JMenu xtrans;
    // End of variables declaration//GEN-END:variables
}
