/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.pembatalan;

import dao.BasePresenter;
import dao.PenjualanModel;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ui.penjualan.PenjualanMvpView;
import ui.penjualan.PenjualanPresenterImpl;
import utils.Config;
import utils.DialogFactory;
import utils.StringHelper;

/**
 *
 * @author Aldhi Ramdan
 */
public class Pembatalan extends javax.swing.JFrame implements PenjualanMvpView {

    PenjualanPresenterImpl mPresenter;

    /**
     * Creates new form Ticket
     */
    public Pembatalan() {
        mPresenter = new PenjualanPresenterImpl();
        mPresenter.attachView(this);
        initComponents();
        formReadyToFilled(true);
        setDefaultButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPenjualan = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtIdPenjualan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNamaPelanggan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtMaskapai = new javax.swing.JTextField();
        btnSearchPenjualan = new javax.swing.JButton();
        txtTelpPelanggan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnCancelOrder = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        txtKelas = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTujuan = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        txtHarga1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtTglBooking = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data Penjualan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, -1));

        tblPenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPenjualanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPenjualan);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 680, 250));

        jLabel2.setText("Kode Booking");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 120, -1));

        txtIdPenjualan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtIdPenjualan.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        jPanel1.add(txtIdPenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 90, 30));

        jLabel3.setText("Pelanggan");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 90, -1));
        jPanel1.add(txtNamaPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 450, -1));

        jLabel8.setText("Maskapai");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 80, 20));

        txtMaskapai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaskapaiActionPerformed(evt);
            }
        });
        txtMaskapai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMaskapaiKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMaskapaiKeyTyped(evt);
            }
        });
        jPanel1.add(txtMaskapai, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 230, -1));

        btnSearchPenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Cari2.png"))); // NOI18N
        btnSearchPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchPenjualanActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearchPenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 40, 30));

        txtTelpPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelpPelangganActionPerformed(evt);
            }
        });
        txtTelpPelanggan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelpPelangganKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelpPelangganKeyTyped(evt);
            }
        });
        jPanel1.add(txtTelpPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 230, -1));

        jLabel9.setText("Telepon");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 80, 20));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        btnCancelOrder.setBackground(new java.awt.Color(204, 204, 255));
        btnCancelOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Hapus.png"))); // NOI18N
        btnCancelOrder.setText("Batalkan");
        btnCancelOrder.setToolTipText("Klik untuk logout pengguna");
        btnCancelOrder.setFocusable(false);
        btnCancelOrder.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelOrder.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelOrderActionPerformed(evt);
            }
        });

        btnRefresh.setBackground(new java.awt.Color(204, 204, 255));
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Pembelian.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.setToolTipText("Klik untuk logout pengguna");
        btnRefresh.setFocusable(false);
        btnRefresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRefresh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCancelOrder)
                .addGap(1, 1, 1)
                .addComponent(btnRefresh)
                .addGap(0, 518, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelOrder)
                    .addComponent(btnRefresh))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 710, 80));

        txtKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKelasActionPerformed(evt);
            }
        });
        txtKelas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKelasKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKelasKeyTyped(evt);
            }
        });
        jPanel1.add(txtKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 230, -1));

        jLabel10.setText("Kelas");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 80, 20));

        txtTujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTujuanActionPerformed(evt);
            }
        });
        txtTujuan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTujuanKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTujuanKeyTyped(evt);
            }
        });
        jPanel1.add(txtTujuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 230, -1));

        jLabel11.setText("Tujuan");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 80, 20));

        jLabel12.setText("Jumlah");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 80, 20));

        txtJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahActionPerformed(evt);
            }
        });
        txtJumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtJumlahKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtJumlahKeyTyped(evt);
            }
        });
        jPanel1.add(txtJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 230, -1));

        jLabel13.setText("Harga");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 60, 20));

        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });
        txtHarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHargaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHargaKeyTyped(evt);
            }
        });
        jPanel1.add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 230, -1));

        txtHarga1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHarga1ActionPerformed(evt);
            }
        });
        txtHarga1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHarga1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHarga1KeyTyped(evt);
            }
        });
        jPanel1.add(txtHarga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 230, -1));

        jLabel14.setText("Tgl Berangkat");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 110, 20));

        txtTglBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTglBookingActionPerformed(evt);
            }
        });
        txtTglBooking.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTglBookingKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTglBookingKeyTyped(evt);
            }
        });
        jPanel1.add(txtTglBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 190, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblPenjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPenjualanMouseClicked
        // TODO add your handling code here:
        int baris = tblPenjualan.getSelectedRow();
        String id = tblPenjualan.getModel().getValueAt(baris, 0).toString();
        PenjualanModel model = mPresenter.findById(id);
        
        txtIdPenjualan.setText(model.idPenjualan);
        txtTglBooking.setText(model.tglBerangkat);
        txtNamaPelanggan.setText(model.namaPelanggan);
        txtTelpPelanggan.setText(model.teleponPelanggan);
        txtMaskapai.setText(model.maskapai);
        txtKelas.setText(model.kelas);
        txtTujuan.setText(model.tujuan);
        txtJumlah.setText(String.valueOf(model.jumlahTiket));
        txtHarga.setText(String.valueOf(model.harga));
    }//GEN-LAST:event_tblPenjualanMouseClicked

    private void txtMaskapaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaskapaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaskapaiActionPerformed

    private void txtMaskapaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaskapaiKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaskapaiKeyPressed

    private void txtMaskapaiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaskapaiKeyTyped
        // TODO add your handling code here:
        //validasi data harus angka atau tombol backspace
        char karakter = evt.getKeyChar();
        if (!(Character.isDigit(karakter) || karakter == KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtMaskapaiKeyTyped

    private void btnSearchPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchPenjualanActionPerformed
        mPresenter.searchById(tblPenjualan, "");
        clearForm();
    }//GEN-LAST:event_btnSearchPenjualanActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        ImageIcon img = new ImageIcon("src/gambar/kredit.png");
        setIconImage(img.getImage());
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        showDataTable();
    }//GEN-LAST:event_formWindowOpened

    private void txtTelpPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelpPelangganActionPerformed
    }//GEN-LAST:event_txtTelpPelangganActionPerformed

    private void txtTelpPelangganKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelpPelangganKeyPressed
    }//GEN-LAST:event_txtTelpPelangganKeyPressed

    private void txtTelpPelangganKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelpPelangganKeyTyped
    }//GEN-LAST:event_txtTelpPelangganKeyTyped

    private void btnCancelOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelOrderActionPerformed
        if (StringHelper.isNotEmpty(txtIdPenjualan.getText())) {
            int pesan = JOptionPane.showConfirmDialog(null, "Batalkan Pesanan?", "", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (pesan == JOptionPane.YES_OPTION) {
                mPresenter.cancelOrder(txtIdPenjualan.getText());
            }
        } 
    }//GEN-LAST:event_btnCancelOrderActionPerformed

    private void txtKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKelasActionPerformed

    private void txtKelasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKelasKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKelasKeyPressed

    private void txtKelasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKelasKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKelasKeyTyped

    private void txtTujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTujuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTujuanActionPerformed

    private void txtTujuanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTujuanKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTujuanKeyPressed

    private void txtTujuanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTujuanKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTujuanKeyTyped

    private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahActionPerformed

    private void txtJumlahKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJumlahKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahKeyPressed

    private void txtJumlahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJumlahKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahKeyTyped

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void txtHargaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHargaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaKeyPressed

    private void txtHargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHargaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaKeyTyped

    private void txtHarga1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHarga1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHarga1ActionPerformed

    private void txtHarga1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHarga1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHarga1KeyPressed

    private void txtHarga1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHarga1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHarga1KeyTyped

    private void txtTglBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTglBookingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTglBookingActionPerformed

    private void txtTglBookingKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTglBookingKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTglBookingKeyPressed

    private void txtTglBookingKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTglBookingKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTglBookingKeyTyped

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        clearForm();
        showDataTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pembatalan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelOrder;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearchPenjualan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPenjualan;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtHarga1;
    private javax.swing.JTextField txtIdPenjualan;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtKelas;
    private javax.swing.JTextField txtMaskapai;
    private javax.swing.JTextField txtNamaPelanggan;
    private javax.swing.JTextField txtTelpPelanggan;
    private javax.swing.JTextField txtTglBooking;
    private javax.swing.JTextField txtTujuan;
    // End of variables declaration//GEN-END:variables

    @Override
    public void clearForm() {
        txtIdPenjualan.setText("");
        txtTglBooking.setText("");
        txtNamaPelanggan.setText("");
        txtTelpPelanggan.setText("");
        txtMaskapai.setText("");
        txtKelas.setText("");
        txtTujuan.setText("");
        txtJumlah.setText("");
        txtHarga.setText("");
    }

    @Override
    public void setDefaultButton() {
        btnSearchPenjualan.setEnabled(true);
    }

    @Override
    public void formReadyToFilled(boolean enabled) {
        txtTglBooking.setEnabled(enabled);
        txtNamaPelanggan.setEnabled(enabled);
        txtTelpPelanggan.setEnabled(enabled);
        txtMaskapai.setEnabled(enabled);
        txtKelas.setEnabled(enabled);
        txtTujuan.setEnabled(enabled);
        txtJumlah.setEnabled(enabled);
        txtHarga.setEnabled(enabled);
    }

    @Override
    public void onError(BasePresenter.DataAccessType dataAccessType) {
        DialogFactory.dialogError("Pesan", "Terjadi gangguan pada database, silahkan coba lagi");
    }

    private void showDataTable() {
        DefaultTableModel data = new DefaultTableModel(null, Config.TABLE_HEADER_PEMBATALAN);
        tblPenjualan.setModel(data);
        ArrayList<PenjualanModel> list = mPresenter.getData();
        if (list != null) {
            for (PenjualanModel item : list) {
                String column[] = {item.idPenjualan, item.tglBerangkat, item.namaPelanggan, item.maskapai, item.kelas, item.tujuan, String.valueOf(item.harga), item.status};
                data.addRow(column);
            }
        }
    }

    @Override
    public void onSucceed(BasePresenter.DataAccessType dataAccessType, PenjualanModel model) {
        if (model != null) {
            DialogFactory.showDialog(model.message);
            showDataTable();
            clearForm();
        }
    }
}
